application: bongapp
version: dev
runtime: python
api_version: 1



builtins:
- datastore_admin: on



error_handlers:
- error_code: over_quota
  file: errors/quota.html

- error_code: dos_api_denial
  file: errors/dos.html

- error_code: timeout
  file: errors/timeout.html

#- file: errors/default.html



handlers:

#static files
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /javascript
  static_dir: static/javascript

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /favicon.ico
  static_files: static/images/favicon.png
  upload: static/images/favicon.png

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt


#public controllers
- url: /
  script: controllers/dashboard.py

#Old systems login/logout
- url: /oldauth
  script: controllers/oldauth.py
  login: required

- url: /oldauth_exit
  script: controllers/oldauth.py


#protected controllers
- url: /bulka
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /search(.*)
  script: controllers/search.py
  login: required

- url: /person(.*)
  script: controllers/person.py
  login: required

- url: /curriculum(.*)
  script: controllers/curriculum.py
  login: required

- url: /dictionary(.*)
  script: controllers/dictionary.py
  login: required

- url: /delete(.*)
  script: controllers/delete.py
  login: required

- url: /update(.*)
  script: controllers/update.py
  login: required

- url: /feedback(.*)
  script: controllers/feedback.py
  login: required

- url: /questionary(.*)
  script: controllers/questionary.py
  login: required
