application: bonga-bonga
version: dev
runtime: python
api_version: 1

handlers:

#static files
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /javascript
  static_dir: static/javascript

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico



#bulka
- url: /bulka
  script: controllers/bulka.py



#public controllers
- url: /
  script: controllers/frontpage.py

- url: /_ah/login_required
  script: controllers/openid_login.py

- url: /activate(.*)
  script: controllers/activate.py



#protected controllers
- url: /dashboard
  script: controllers/dashboard.py
  login: required

- url: /person(.*)
  script: controllers/person.py
  login: required

- url: /user(.*)
  script: controllers/user.py
  login: required

- url: /classifier(.*)
  script: controllers/classifier.py
  login: required
