application: bubbledu
version: dev
runtime: python
api_version: 1



builtins:
- datastore_admin: on



error_handlers:
- error_code: over_quota
  file: errors/quota.html

- error_code: dos_api_denial
  file: errors/dos.html

- error_code: timeout
  file: errors/timeout.html

#- file: errors/default.html



# skip_files:
# - ^(.*/)?.*\.less
# - ^(.*/)?\..*



handlers:

#static files
- url: /css
  static_dir: static/css
  #expiration: "1d"

- url: /fonts
  static_dir: static/fonts
  #expiration: "1d"

- url: /images
  static_dir: static/images
  expiration: "1d"

- url: /javascript
  static_dir: static/javascript
  expiration: "90d"

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: "90d"

- url: /favicon.ico
  static_files: static/images/favicon.png
  upload: static/images/favicon.png
  expiration: "90d"



#public controllers
- url: /application(.*)
  script: controllers/application.py

- url: /document(.*)
  script: controllers/document.py

- url: /xml(.*)
  script: controllers/public_xml.py

- url: /ical(.*)
  script: controllers/ical.py



#Old systems login/logout
- url: /oldauth
  script: controllers/oldauth.py
  login: required

- url: /oldauth_exit
  script: controllers/oldauth.py


#protected controllers
- url: /
  script: controllers/dashboard.py
  login: required

- url: /dashboard(.*)
  script: controllers/dashboard.py
  login: required

- url: /person(.*)
  script: controllers/person.py
  login: required

- url: /btype(.*)
  script: controllers/bubbletype.py
  login: required

- url: /bubbletype(.*)
  script: controllers/bubble.py
  login: required

- url: /bubble(.*)
  script: controllers/bubble.py
  login: required

- url: /rating(.*)
  script: controllers/rating.py
  login: required

- url: /preferences(.*)
  script: controllers/preferences.py
  login: required

- url: /spam(.*)
  script: controllers/spam.py
  login: required

- url: /gapps(.*)
  script: controllers/googleapps.py
  login: required

- url: /update(.*)
  script: controllers/update.py
  login: admin

- url: /feedback(.*)
  script: controllers/feedback.py
  login: required

- url: /reception(.*)
  script: controllers/reception.py
  login: required



#admin only controllers
- url: /bulka
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /cron(.*)
  script: controllers/cron.py
  login: admin

- url: /taskqueue(.*)
  script: controllers/taskqueue.py
  login: admin

- url: /zimport(.*)
  script: controllers/zimport.py
  login: admin

- url: /backup(.*)
  script: controllers/backup.py
  login: admin

- url: /questionary(.*)
  script: controllers/questionary.py
  login: admin
